services:
  - type: web
    name: contentcartel-web
    runtime: docker
    dockerfilePath: ./Dockerfile.web
    dockerContext: .
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: contentcartel-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    plan: free
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production